network_config:
  symmetry_win: False
  NFFT: 256
  window_len: 256
  hop_size: 48
  compression: "sqrt"
  eband_num: 96
  gru1_size: 96
  gru2_size: 96
  M: 32

DDP:
  world_size: 2

optimizer:
  lr: 0.001

scheduler:
  kwargs:
    warmup_steps: 10000
    decay_until_step: 200000
    max_lr: 0.001
    min_lr: 1.0e-07
  update_interval: step
  # name: ReduceLROnPlateau
  # kwargs:
  #   mode: min           # 如果监测的是 loss 用 min，分数用 max
  #   factor: 0.5         # 学习率降低倍数
  #   patience: 2         # 连续多少个 epoch 没提升就降低
  #   min_lr: 1e-7        # 最小学习率
  #   threshold: 1e-3     # 提升的最小幅度
  #   cooldown: 0         # 冷却期
  #   eps: 1e-8
  # use_plateau: true
  # update_interval: epoch

FFT:
  n_fft: 256
  hop_length: 48
  win_length: 256

loss:
  n_fft: ${FFT.n_fft}
  hop_len: ${FFT.hop_length}
  win_len: ${FFT.win_length}
  compress_factor: 0.3
  eps: 1e-12
  lamda_ri: 30
  lamda_mag: 70

train_dataset: 
  clean_file_path: 'prepare_datasets/train_clean_24k.csv'
  noise_file_path: 'prepare_datasets/train_noise_24k_new.csv'
  rir_file_path: 'prepare_datasets/train_rir_24k.csv'
  fs: 24000
  length_in_seconds: 8
  num_data_per_epoch: 100000
  train: True
  snr_db: [0, 25]
  dr_db: [-35, -15]
  pure_noise_prob: 0.1
  random_seed: 0511
  max_readers: 256

train_dataloader: 
  batch_size: 32
  num_workers: 4
  drop_last: True
  pin_memory: True     # 启用锁页内存
  prefetch_factor: 2     # 每个worker预取2个batch
  persistent_workers: True # 保持worker进程  

validation_dataset: 
  clean_file_path: 'prepare_datasets/val_clean_24k.csv'
  noise_file_path: 'prepare_datasets/val_noise_24k_new.csv'
  rir_file_path: 'prepare_datasets/val_rir_24k.csv'
  fs: 24000
  length_in_seconds: 8
  num_data_per_epoch: 20000
  train: False
  snr_db: [0, 25]
  dr_db: [-35, -15]
  pure_noise_prob: 0.1
  random_seed: 2021
  max_readers: 256

validation_dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: True     # 启用锁页内存
  prefetch_factor: 2     # 每个worker预取2个batch
  persistent_workers: True # 保持worker进程  

samplerate: 24000

trainer:
  epochs: 200
  save_checkpoint_interval: 1
  clip_grad_norm_value: 3.0
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/base_69M_train
  resume: False
  resume_datetime: 2025-11-13-03h26m

lmdb_datasets:
  train_lmdb_path: prepare_datasets/training_audio_24k_noDereverb.lmdb
  valid_lmdb_path: prepare_datasets/validation_audio_24k_noDereverb.lmdb

stage1_model: 