test_dataset: 
  noisy_dir: /minioData/goodman/train_data/ha_lmdb/eval_sets/noisy/
  clean_dir: /minioData/goodman/train_data/ha_lmdb/eval_sets/clean/
  noise_dir: /minioData/goodman/train_data/ha_lmdb/eval_sets/noise/

network:
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/gtcrn_dual_decoder_speechCnoise_2025-10-14-10h18m
  config: ${network.exp_path}/config.yaml
  ckpt_name: model_200
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: /minioData/goodman/train_data/ha_lmdb/eval_sets/enhanced
