test_dataset: 
  noisy_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_NRL_test/noisy/
  clean_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_NRL_test/clean/
  noise_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_NRL_test/noise/

network:
  neg_infer: False
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/gtcrn_30M_fro-mse_irm_tau_2025-12-26-01h34m
  config: ${network.exp_path}/config.yaml
  ckpt_name: best_model_141
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: /minioData/goodman/train_data/ha_lmdb/evalsets_NRL_test/gtcrn_30M_fro-mse_irm_tau
  neg_folder: /minioData/goodman/train_data/ha_lmdb/evalsets_NRL_test/gtcrn_30M_fro-mse_irm_tau_neg
