test_dataset: 
  noisy_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/noisy/
  clean_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/clean/
  noise_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/noise/

network:
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/dfnet_92MMacs_8ch_hybLoss_mrLoss_2025-11-11-06h36m
  config: ${network.exp_path}/config.yaml
  ckpt_name: model_100
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/dfnet_92MMacs_8ch_hybLoss_mrLoss_enh/
