network_config:
  n_fft: ${FFT.n_fft}
  hop_len: ${FFT.hop_length}
  win_len: ${FFT.win_length}

DDP:
  world_size: 2

optimizer:
  lr: 0.001

scheduler:
  kwargs:
    warmup_steps: 50000
    decay_until_step: 150000 #200000
    max_lr: 0.001
    min_lr: 1.0e-07
    init_lr: 0.0001
  update_interval: step
  
FFT:
  n_fft: 128
  hop_length: 48
  win_length: 128

loss:
  n_fft: ${FFT.n_fft}
  hop_len: ${FFT.hop_length}
  win_len: ${FFT.win_length}
  compress_factor: 0.3
  eps: 1e-12
  lamda_ri: 30
  lamda_mag: 70
  # sample_rate: ${samplerate}
  # nfft: ${FFT.n_fft}
  # hop_size: ${FFT.hop_length}
  # K: 25
  # phon: 40
  # eps: 1e-12

ccsdc_loss:
  alpha: 0.3
  beta: 0.3
  fft_size: ${FFT.n_fft}
  norm_flag: False
  eps: 1e-12
  loss_type: 'mse'
  revise_clean: False
  hop_size: ${FFT.hop_length}
  percep_weight: 0.06
  mix_noise: 0.0

train_dataset: 
  clean_file_path: 'prepare_datasets/train_clean_24k.csv'
  noise_file_path: 'prepare_datasets/train_noise_24k_new.csv'
  rir_file_path: 'prepare_datasets/train_rir_24k.csv'
  fs: 24000
  length_in_seconds: 8
  num_data_per_epoch: 100000
  train: True
  snr_db: [0, 25]
  dr_db: [-35, -15]
  pure_noise_prob: 0.05
  random_seed: 1117
  max_readers: 256

train_dataloader: 
  batch_size: 32
  num_workers: 4
  drop_last: True
  pin_memory: True     # 启用锁页内存
  prefetch_factor: 2     # 每个worker预取2个batch
  persistent_workers: True # 保持worker进程  

validation_dataset: 
  clean_file_path: 'prepare_datasets/val_clean_24k.csv'
  noise_file_path: 'prepare_datasets/val_noise_24k_new.csv'
  rir_file_path: 'prepare_datasets/val_rir_24k.csv'
  fs: 24000
  length_in_seconds: 8
  num_data_per_epoch: 20000
  train: False
  snr_db: [0, 25]
  dr_db: [-35, -15]
  pure_noise_prob: 0.05
  random_seed: 2025
  max_readers: 256

validation_dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: True     # 启用锁页内存
  prefetch_factor: 2     # 每个worker预取2个batch
  persistent_workers: True # 保持worker进程  

samplerate: 24000

trainer:
  epochs: 100
  save_checkpoint_interval: 1
  clip_grad_norm_value: 3.0
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/dpcrn_34M_Hyber_loss_train_128size_clip1.0
  resume: False
  resume_datetime: 2025-11-13-03h26m

lmdb_datasets:
  train_lmdb_path: ./prepare_datasets/training_audio_tau_24k_noDereverb.lmdb
  valid_lmdb_path: ./prepare_datasets/validation_audio_tau_24k_noDereverb.lmdb

stage1_model: 