network_config:
  n_fft: ${FFT.n_fft}
  hop_len: ${FFT.hop_length}
  win_len: ${FFT.win_length}

DDP:
  world_size: 2

optimizer:
  lr: 0.001

scheduler:
  kwargs:
    warmup_steps: 6000
    decay_until_step: 60000
    max_lr: 0.0001
    min_lr: 1.0e-06
    init_lr: 0.00003
  update_interval: step
  
FFT:
  n_fft: 128
  hop_length: 48
  win_length: 128

loss:
  n_fft: ${FFT.n_fft}
  hop_len: ${FFT.hop_length}
  win_len: ${FFT.win_length}
  compress_factor: 0.3
  eps: 1e-12
  lamda_ri: 30
  lamda_mag: 70
  # sample_rate: ${samplerate}
  # nfft: ${FFT.n_fft}
  # hop_size: ${FFT.hop_length}
  # K: 25
  # phon: 40
  # eps: 1e-12

stft_loss:
  n_fft: ${FFT.n_fft}
  hop_len: ${FFT.hop_length}
  win_len: ${FFT.win_length}
  window: 'hann_window'
  weight_sc: 10.0
  weight_mag: 100.0

ccsdc_loss:
  alpha: 0.3
  beta: 0.3
  fft_size: ${FFT.n_fft}
  norm_flag: False
  eps: 1e-12
  loss_type: 'mse'
  revise_clean: False
  hop_size: ${FFT.hop_length}
  percep_weight: 0.06
  mix_noise: 0.0

train_dataset: 
  clean_file_path: 'prepare_datasets/train_clean_24k.csv'
  noise_file_path: 'prepare_datasets/train_noise_picked_dns.csv'
  rir_file_path: 'prepare_datasets/train_rir_24k.csv'
  fs: 24000
  length_in_seconds: 8
  num_data_per_epoch: 100000
  train: True
  snr_db: [0, 25]
  dr_db: [-40, -20]
  pure_noise_prob: 0.0
  random_seed: 1987
  max_readers: 256

train_dataloader: 
  batch_size: 96
  num_workers: 8
  drop_last: True
  pin_memory: True     # 启用锁页内存
  prefetch_factor: 2     # 每个worker预取2个batch
  persistent_workers: True # 保持worker进程  

validation_dataset: 
  clean_file_path: 'prepare_datasets/val_clean_24k.csv'
  noise_file_path: 'prepare_datasets/val_noise_picked_dns.csv'
  rir_file_path: 'prepare_datasets/val_rir_24k.csv'
  fs: 24000
  length_in_seconds: 8
  num_data_per_epoch: 20000
  train: False
  snr_db: [0, 25]
  dr_db: [-40, -20]
  pure_noise_prob: 0.0
  random_seed: 2026
  max_readers: 256

validation_dataloader:
  batch_size: 96
  num_workers: 8
  pin_memory: True     # 启用锁页内存
  prefetch_factor: 2     # 每个worker预取2个batch
  persistent_workers: True # 保持worker进程  

samplerate: 24000

trainer:
  epochs: 200
  save_checkpoint_interval: 1
  clip_grad_norm_value: 1
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/gtcrn_30M_hyber_irm_pickDNS
  resume: True
  resume_datetime: 2026-01-08-11h44m

lmdb_datasets:
  train_lmdb_path: ./prepare_datasets/training_audio_pickDNS_24k_noDereverb.lmdb
  valid_lmdb_path: ./prepare_datasets/validation_audio_pickDNS_24k_noDereverb.lmdb

stage1_model: 