test_dataset: 
  noisy_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/noisy/
  clean_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/clean/
  noise_dir: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/noise/

network:
  exp_path: /data/goodman/torch_nn_train/SEtrain/Ha_denoise/Ha_base_69MMacs
  config: ${network.exp_path}/config.yaml
  ckpt_name: Model
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: /minioData/goodman/train_data/ha_lmdb/evalsets_noReverb/Ha_base_69MMacs_enh/
